In [1]:
from tensorflow import keras
from keras.layers import Dense,SimpleRNN
from keras import Sequential


ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [4]:
model = Sequential()

In [5]:
model.add(SimpleRNN(3,input_shape=(4,5))) # what is (4,5) ? (timesteps,features)
model.add(Dense(1,activation='sigmoid'))

In [6]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [9]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.16244704, -0.07830232,  0.7737275 ],
       [-0.12704086, -0.26188803, -0.6740148 ],
       [-0.43085748,  0.55581456, -0.47184473],
       [-0.01228017,  0.511264  ,  0.24040622],
       [ 0.39569038,  0.5439407 ,  0.0011422 ]], dtype=float32)

In [10]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[ 0.5449486 ,  0.51792103, -0.6593852 ],
       [-0.7956927 ,  0.56742024, -0.21191368],
       [ 0.26439393,  0.64015   ,  0.72132087]], dtype=float32)

In [11]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [12]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[-1.0244219 ],
       [-0.95579886],
       [ 0.49502683]], dtype=float32)

In [13]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)