In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split

In [2]:
(X, y) = make_moons(n_samples=1000, noise=0.1, random_state=42)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
model = Sequential()

In [8]:
model.add(Dense(2, input_dim=2, activation='relu', kernel_initializer='zero'))
model.add(Dense(2, input_dim=2, activation='relu', kernel_initializer='zero'))
model.add(Dense(1, activation='sigmoid', kernel_initializer='zero'))

In [9]:
model.get_weights()

[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0., 0.],
        [0., 0.]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.],
        [0.]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
weights = model.get_weights()  # get the shapes
new_weights = [np.full(w.shape, 0.5, dtype=np.float32) for w in weights]
model.set_weights(new_weights)


In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
25/25 [==============================] - 1s 11ms/step - loss: 2.5675 - accuracy: 0.5000 - val_loss: 2.4703 - val_accuracy: 0.5000
Epoch 2/10
25/25 [==============================] - 0s 5ms/step - loss: 2.1732 - accuracy: 0.5000 - val_loss: 2.1047 - val_accuracy: 0.5000
Epoch 3/10
25/25 [==============================] - 0s 5ms/step - loss: 1.8624 - accuracy: 0.5000 - val_loss: 1.8069 - val_accuracy: 0.5000
Epoch 4/10
25/25 [==============================] - 0s 5ms/step - loss: 1.6106 - accuracy: 0.5000 - val_loss: 1.5819 - val_accuracy: 0.5000
Epoch 5/10
25/25 [==============================] - 0s 5ms/step - loss: 1.4199 - accuracy: 0.5000 - val_loss: 1.3957 - val_accuracy: 0.5000
Epoch 6/10
25/25 [==============================] - 0s 4ms/step - loss: 1.2666 - accuracy: 0.5000 - val_loss: 1.2544 - val_accuracy: 0.5000
Epoch 7/10
25/25 [==============================] - 0s 4ms/step - loss: 1.1488 - accuracy: 0.5000 - val_loss: 1.1429 - val_accuracy: 0.5000
Epoch 8/10
25/25 [=

In [ ]:
# No training will occur since weights are initialized to zero
# and then set to a constant value, which does not allow for learning.
# The model will not learn anything meaningful from the data.
# This is just an example to illustrate the concept of non-zero weight initialization.