In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split


In [2]:
(X, y) = make_moons(n_samples=1000, noise=0.1, random_state=42)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
model = Sequential()

In [5]:
model.add(Dense(2, input_dim=2, activation='relu', kernel_initializer='zeros'))
model.add(Dense(2, activation='relu', kernel_initializer='zeros'))
model.add(Dense(1, activation='sigmoid', kernel_initializer='zeros'))

In [7]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [8]:
model.get_weights()

[array([[0., 0.],
        [0., 0.]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0., 0.],
        [0., 0.]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.],
        [0.]], dtype=float32),
 array([0.], dtype=float32)]

#### Here we can see that the weights are initialized to zero
#### thats why the model is not learning anything because the gradients are also zero
#### because the relu activation function will output zero for any negative input
#### and the sigmoid activation function will output 0.5 for any input
#### tanh activation function will give the same problem

In [9]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
25/25 [==============================] - 3s 13ms/step - loss: 0.6932 - accuracy: 0.4875 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 2/10
25/25 [==============================] - 0s 5ms/step - loss: 0.6932 - accuracy: 0.5000 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 3/10
25/25 [==============================] - 0s 5ms/step - loss: 0.6932 - accuracy: 0.5000 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 4/10
25/25 [==============================] - 0s 5ms/step - loss: 0.6932 - accuracy: 0.5000 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 5/10
25/25 [==============================] - 0s 5ms/step - loss: 0.6932 - accuracy: 0.5000 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 6/10
25/25 [==============================] - 0s 6ms/step - loss: 0.6932 - accuracy: 0.4725 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 7/10
25/25 [==============================] - 0s 5ms/step - loss: 0.6932 - accuracy: 0.4875 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 8/10
25/25 [=